"use client";
import Head from "next/head";
import Image from "next/image";
import mobileview from "@/../public/home/section6.png"; // Ensure the image is in the public folder

import { useState } from "react";

export default function Section6() {
  return (
    <div className=" bg-white lg:h-[400px]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col pt-10 lg:px-32 ">
        <p className="text-center text-black text-2xl px-10 lg:px-0 font-extrabold mb-12">
          More Efficient Than Owning <br /> Your Own Fleet
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mx-12">
          <div className="bg-slate cursor-pointer flex flex-col p-6 text-center justify-center items-center shadow-md">
            <h3 className="text-lg font-bold mb-2">
              You are not limited <br /> by your vehicle
            </h3>
            <p className="text-sm px-12">
              As soon as the need arises, your employees can order a ride or
              delivery
            </p>
          </div>
          <div className="bg-slate cursor-pointer flex flex-col text-center justify-center items-center p-6  shadow-md">
            <h3 className="text-xl font-bold mb-2">
              Intended use <br /> only
            </h3>
            <p className="text-sm px-12">
              You pay only for the services actually rendered and only within
              the limits
            </p>
          </div>
          <div className="bg-slate cursor-pointer flex flex-col justify-center items-center text-center p-6  shadow-md">
            <h3 className="text-xl font-bold mb-2">Favourite Driver</h3>
            <p className="text-sm px-12">Create your own fleet using OZ Ove</p>
          </div>
        </div>
      </main>
    </div>
  );
}
